ForgeRock/secret-agent

- pkg/generator/generator.go
- pkg/generator/rsa_test.go
- pkg/memorystore/memorystore.go
- pkg/memorystore/test/helpers.go
This one makes sure all aliases are dependency tree parents on the secret key they belong to, so that when we go to generate the keystore itself, the aliases are all ready.
Also fixed a typo and replaced placeholders that were causing tests to fail.
> All aliases should be parents of relevant secret key

- pkg/types/types.go
- pkg/types/types_test.go
- secretsConfig.yaml
As the title says. Simon updated me that we would need a passwordPath for the deployment key for CAs in keystores.
All tests passing.
> Add validation for new passwordPath for TypeCA

- pkg/memorystore/memorystore.go
- pkg/memorystore/memorystore_test.go
- pkg/memorystore/test/helpers.go
PasswordPath was needed for deployment key CA, this adds tests for it to the other half of the example test scenarios.
Remove duplicated parent and child nodes in dependency tree when two or more paths lead to the same node.
> Improve passwordPath testing, remove duplicated nodes

- pkg/memorystore/memorystore.go
- pkg/memorystore/memorystore_test.go
- pkg/memorystore/test/helpers.go
- pkg/types/types.go
- pkg/types/types_test.go
StorePassPath and KeyPassPath should be parents of all aliases. Ensure tests support this.
Refactor dependency tree calculation to be much faster. Sort Parents and Children slices in tests to make refactoring easier and reduce brittleness during development.
Also, Algorithm and CommonName should not be part of TypeCA.
Increase configuration validation.
> StorePassPath and KeyPassPath should parent all aliases, refactor

- hooks/post_push
This is a Dockerhub post_push hook to tag docker images with the git commit id.
Note: Dockerhub is setup to build+push images when pushing code to master. So this will not run as part of the PR docker build checks we have for PRs.
Closes #3
> Tag docker images with the git commit id

- README.md
- config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
- pkg/generator/generator.go
1. Update README.md
1. Commented out `truststore` keytype from sample sac. See issue #48
1. Add a placeholder for TypeJCEKS. Cant create empty secrets in AWS
> Update readme + misc fixes to enable secretmanager

- Makefile
- controllers/secretagentconfiguration_controller.go
1. Add owner reference to generated secrets
1. Update the SAC status when the reconcile loop is done
closes #61
> Add owner reference and update status

- controllers/secretagentconfiguration_controller.go
- pkg/generator/certificate.go
- pkg/generator/certificate_test.go
- pkg/generator/literal.go
- pkg/generator/literal_test.go
- pkg/generator/password.go
- pkg/generator/rootca.go
- pkg/generator/rootca_test.go
1. Implement Literal KeyConfigType
1. Make NewRootCA consistent with other generators. Returns error
1. Fix typos in password.go
closes #64
> Implement Literal KeyConfigType

- api/v1alpha1/secretagentconfiguration_types.go
- api/v1alpha1/secretagentconfiguration_types_test.go
- api/v1alpha1/secretagentconfiguration_webhook.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
- config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
- controllers/secretagentconfiguration_controller.go
- controllers/webhook_cabundler.go
- pkg/generator/certificate.go
- pkg/generator/certificate_test.go
- pkg/generator/generator.go
- pkg/generator/literal.go
- pkg/generator/password.go
- pkg/generator/rootca.go
- pkg/generator/rootca_test.go
1. Update the webhook_cabundler to use new ca and keypair generate funcs
1. Make distinguishedName a required field for ca key type
1.  Add `duration` to keyConfig.KeySpec to be used by `ca`,  `keypair`
1. Update sample secret-agent config
1. Implement duration for ca key types
1. Implement distinguishedName for ca key types
1. Fix bug in webhook.Defaulter when calling cleanUpPaths
1. Change NewRootCa to take a KeyConfig as argument
1. Clean up unused code from certificate.go and related tests
1. Update tests to account for changes mentioned above
1. Update ConfigurationStructLevelValidator to account for changes above
Closes #59
> Enhancements to webhooks, webhook certs, tests, types

- api/v1alpha1/secretagentconfiguration_types.go
- api/v1alpha1/secretagentconfiguration_types_test.go
- api/v1alpha1/secretagentconfiguration_webhook.go
- api/v1alpha1/v1alpha1_test.go
- config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
- config/manager/manager.yaml
- config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
- go.mod
- pkg/generator/keytool.go
- pkg/generator/keytoolgenkeypair.go
- pkg/generator/keytoolgenkeypair_test.go
- pkg/generator/keytoolimportpassword.go
1. Implement new genkeypair alias cmd for the keytool secret type.
1. Remove DestinationPath. This is not required to genKeyPair
1. Add more elements to the sample SAC
1. Increase CPU limit to 1000m. Keytool operations are power hungry
closes #78
> Implement genkeypair cmd for keytool type

- controllers/secretagentconfiguration_controller.go
- pkg/generator/certificate.go
- pkg/generator/certificate_test.go
- pkg/generator/importpassword_test.go
- pkg/generator/keytool.go
- pkg/generator/keytoolgenkeypair_test.go
- pkg/generator/keytoolimportpassword.go
- pkg/generator/truststore.go
- pkg/generator/truststore_test.go
Controller stores reference data using both slices returned from
References(). The keyname pattern is "slice1[i]/slice2[i]". For most
KeyMgrs this will match the pattern used in the Spec. Root Certs and SSH
keys are different and use specific names always.
KeyMgr.LoadReferenceData(data) should now expect to data to be keyed "slice1[i]/slice2[i]"
closes #84
> controller stores reference secrets using composite of name and data key

- controllers/secretagentconfiguration_controller.go
- pkg/generator/certificate.go
- pkg/generator/certificate_test.go
- pkg/generator/keytool.go
- pkg/generator/keytoolgenkeypair_test.go
- pkg/generator/keytoolgenseckey.go
- pkg/generator/keytoolgenseckey_test.go
- pkg/generator/rootca.go
Implement genseckey cmd for keytool type
1. Implement new genseckey alias cmd for keytool type
1. Fix bug with keypass and storepass assigned to the wrong variable
closes #79
Fix reference path bugs
1. Reconciler was referencing wrong key names when loading secret data
1. certificates should return references to priv and pub components
1. Removed hardcoded names from certificate.go. Use Key names provided
> Implement genseckey cmd for keytool type

- api/v1alpha1/secretagentconfiguration_types.go
- config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
- config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
- pkg/generator/certificate.go
- pkg/generator/certificate_test.go
- pkg/generator/generator.go
- pkg/generator/keytool.go
- pkg/generator/keytoolimportpassword.go
- pkg/generator/keytoolimportstore.go
- pkg/generator/keytoolimportstore_test.go
- pkg/generator/rootca.go
- pkg/generator/rootca_test.go
- pkg/generator/truststore.go
- pkg/generator/truststore_test.go
RootCA now serializes itself to secrets the key of `name` e.g: 
```
- name: platform-ca
keys:
>>    - name: ca
```
Is stored in the secret platform-ca as `ca.pem` and `ca-private.pem`
> Import keystore aliasmgr

- api/v1alpha1/secretagentconfiguration_types.go
- api/v1alpha1/secretagentconfiguration_webhook.go
- config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
- config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
- config/samples/secretManager/cloud-credentials.yaml
- controllers/secretagentconfiguration_controller.go
- go.mod
- go.sum
- pkg/generator/certificate.go
- pkg/generator/keytool.go
- pkg/generator/truststore.go
- pkg/secretsmanager/secretsmanager.go
1. Add support for AWS secret manager
1. Fix bug in isEmpty for KeyPairs
1. Credentials to access the secret mgr are now passed through a secret ref in the SAC using `credentialsSecretName`
1. Retry reconcile loop if error with secret manager.
1. Temporary bypass secret manager for keytool and truststore #80 #111
closes #109, closes #49
> Add support for AWS secret manager

- README.md
- config/manager/manager.yaml
- controllers/secretagentconfiguration_controller.go
- main.go
1. Users can force the NS the operator uses to source cloud creds
1. The NS is provided using ` --cloud-secrets-namespace` runtime arg.
1. If the arg is omitted, it assumes the creds NS is the same as the SAC
1. The sample deployment uses the same NS as the operator by default
1. Update the README.md to account for these changes.
Closes #133
> Ability to select the source NS for cloud creds

- README.md
- api/v1alpha1/secretagentconfiguration_types.go
- api/v1alpha1/secretagentconfiguration_webhook.go
- config/rbac/service_account.yaml
- config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
- config/samples/secretManager/cloud-credentials.yaml
- controllers/secretagentconfiguration_controller.go
1. Add support for GCP workload identity
1. Update README with new steps to enable workload identity
1. Add GCP secret manager fields to the sample SAC.
1. Make "managed identities" the default authentication method for Azure AKS
Closes #132
> Add support for GCP workload identity

- Makefile
- config/webhook/manifests.yaml
1. Remove `caBundle` from webhook conf to avoid accidental overwrite
Closes #142
> Remove `caBundle` from webhook configuration

- controllers/secretagentconfiguration_controller.go
- go.mod
- go.sum
- pkg/generator/certificate.go
- pkg/generator/generator.go
- pkg/generator/keytool.go
- pkg/generator/literal.go
- pkg/generator/password.go
- pkg/generator/ssh.go
- pkg/generator/truststore.go
- pkg/secretsmanager/secretsmanager.go
Create newSecretManager function to create a new cloud vendor specific SecretManager object.
Create new SecretManager interface to execute loading and adding of secrets and closing of clients.
Move all secret manager logic to the secretsmanager package.
Update generator packages to call the SecretManager interface.
Closes #166
> Refactor Secret Manager Client

- controllers/secretagentconfiguration_controller.go
- go.mod
- pkg/generator/generator.go
- pkg/secretsmanager/secretsmanager.go
Change using ENV VARs to store Secret Manager client credentials.
Instead use secret file directly in GCP Secret Manager client code. Use secret objects directly in AWS/Azure Secret Manager client code.
Remove manageCloudCredentials function and migrate code into the new Secret Manager object functions.
Closes CLOUD-2795
> Remove dependency on ENV VARs to store client credentials

- Makefile
- api/v1alpha1/secretagentconfiguration_types.go
- config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
- controllers/secretagentconfiguration_controller.go
- pkg/k8ssecrets/k8ssecrets.go
1. Reconcile deletes secrets when they are removed from the SAC
1. Fix SAC status
1. Upgrade CRD definition to `apiextensions.k8s.io/v1` (req k8s 1.16+)
1. Set default secret timeout using openAPI
Closes #162
Closes #171
> Reconcile deletes unwanted secrets + fix status

- pkg/generator/certificate.go
Add ClientAuth to certificate template as required by SSL Key Pair.
Remove ServerAuth and ClientAuth usages from CA cert as is not relevant.
This is required for CLOUD-2920 - Implement Trust Manager Provider.
ref: CLOUD-3042
> fix: Certificate Key Usages

- Makefile
- pkg/generator/certificate.go
1. Add "combined" output for PEM keypairs
1. "Combined" output contains private + public keys in a single PEM file
1. Add `ENABLE_WEBHOOKS=false` to `make run` target to allow the operator to run locally.
> feat: Add "combined" output for PEM keypairs

- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yml
Updated to use Go 1.16, dropped steps that are already required to be run in PR
> fix: update release workflow

- README.md
Update service account name in readme for Google Cloud Secret Manager access with Workload Identity.
ref: CLOUD-3287
> chore: Update service account name in readme.

- pkg/secretsmanager/secretsmanager.go
The SecretsManagerPrefix field wasn't set in secretManagerAWS struct.
ref: CLOUD-3592
> fix: Add missing prefix to AWS return object

- .gitignore
- README.md
- api/v1alpha1/secretagentconfiguration_types.go
- config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
- pkg/secretsmanager/secretsmanager.go
Adds the ability to supply own KMS key for secret creation.
Addresses #226 
@lee-baines or @jrcast you seem to be still somewhat active on this - any chance of a review on this please?
> fix: add KMSKeyId option to AWS Secrets Manager

- config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
Add back the EC keys which was previously removed as they were thought to be breaking the latest image.
ref: CLOUD-4161
> chore: Add back the EC keys as they are required by AM

- charts/secret-agent/Chart.yaml
- charts/secret-agent/templates/crds/secretagentconfigurations.yaml
- charts/secret-agent/templates/deployment.yaml
- charts/secret-agent/values.yaml
* Support overriding the kube-rbac-proxy image
* Support pod labels
* Add awsKmsKeyId which was missing in the helm template
* Update Chart version to 1.2.2
* Update docker image location
* Update CRD to match formatting in config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
> fix: Helm Chart Updates

- .github/workflows/cluster_deploy.yaml
- Dockerfile
- Makefile
- config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
Update openjdk verion to 23-ea-15-jdk-slim-bullseye to remove several high and medium vulnerabilities.
regards,
Lee
> fix: Update openjdk version to remove vulnerabilities
