main.go
pkg/memorystore/memorystore.go
pkg/memorystore/memorystore_test.go
pkg/types/types.go
secretsConfig.yaml

EnsureAcyclic ensures the config doesn't have circular dependencies, and informs the user if so.

Add EnsureAcyclic

---

Dockerfile
controllers/secretagentconfiguration_controller.go
pkg/k8ssecrets/k8ssecrets.go
pkg/k8ssecrets/k8ssecrets_test.go

1. Fixes #13 : Secret data was getting double base64 encoded
1. Added info logs when creating/updating secrets.

Fix double base64 encoding.

---

Dockerfile.testing
Makefile
README.md
api/v1alpha1/suite_test.go
api/v1alpha1/v1alpha1_test.go
controllers/suite_test.go
pkg/secretsmanager/secretsmanager_integration_test.go

This allows the integration tests to reach out and hit minikube and work.

Allow full test suite to run containerized

---

.github/workflows/go.yaml
Dockerfile.testing
Makefile
README.md
pkg/generator/generator_test.go
pkg/generator/keytool_test.go

Add git actions config to build and test on PRs
Fixes #31

Add git actions config to build and test on PRs

---

Dockerfile
controllers/webhook_cabundler.go

1. We were only using client-go temporarily. Closes #22

Use controller-runtime's client in webhook_cabundler

---

api/v1alpha1/secretagentconfiguration_types.go
api/v1alpha1/secretagentconfiguration_webhook.go
config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
config/manager/kustomization.yaml
config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
pkg/generator/certificate.go
pkg/generator/certificate_test.go
pkg/generator/generator.go
pkg/generator/keytool.go

- Generates certs for opendj encryption
- Fixes issue with lingering keystore inside container
- Generate passwords for opendj

CLOUD-2190: generate certs for opendj

---

main.go

if ENABLE_WEBHOOKS==false skip all webhook initialization and cert gen

fix: Fix ENABLE_WEBHOOKS flag

---

controllers/webhook_cabundler.go

1. Reuse webhook secrets if found in k8s.
2. Change webhook certDir folder permission to 700
Closes #28

Reuse webhook CA and cert if found in a k8s secret

---

.gitignore
controllers/secretagentconfiguration_controller.go
go.mod
go.sum
pkg/generator/password.go
pkg/generator/password_test.go
pkg/generator/rootca.go

1. Implement Password KeyConfigType
2. Add tests
closes #57

Implement Password KeyConfigType

---

api/v1alpha1/secretagentconfiguration_types.go
api/v1alpha1/secretagentconfiguration_webhook.go
config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
pkg/generator/password.go

Use binary characters in passwords when `useBinaryCharacters: true`
closes #89

Add ability to use binary characters in passwords

---

pkg/generator/keytool.go

use absolute paths for external commands

---

api/v1alpha1/secretagentconfiguration_types.go
api/v1alpha1/secretagentconfiguration_webhook.go
config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
pkg/generator/certificate.go
pkg/generator/certificate_test.go

adds ability to self sign and create an expired cert

---

pkg/generator/certificate.go
pkg/generator/rootca.go

1. Implement LoadSecretFromManager and EnsureSecretManager
1.  Update the name referenced by the secretManager in rootCA.go
Closes #55

Implement Secret Manager methods for CertKeyPair

---

Makefile
config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
pkg/generator/certificate.go
pkg/generator/certificate_test.go
pkg/generator/keytool.go
pkg/generator/keytoolimportcert.go
pkg/generator/rootca.go

adds importcert, no usage attributes for negative duration values

---

controllers/secretagentconfiguration_controller.go
pkg/generator/keytool.go
pkg/generator/truststore.go

1. Implement keytool secret manager support
1. Fix error handling when loading secrets from secret manager
Closes #80

Implement keytool secret manager support

---

api/v1alpha1/secretagentconfiguration_types.go
config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
controllers/secretagentconfiguration_controller.go
go.mod
pkg/secretsmanager/secretsmanager.go

1. Add secretsManagerPrefix to AppConfig in the SAC
1. Fix bug with AWS creds. Use  secret only if user provides creds for AWS
1. Add  missing azure secret manager function. WIP
Closes #115

Add secretsManagerPrefix to appConfig in the SAC

---

pkg/generator/importpassword_test.go
pkg/generator/keytool.go
pkg/generator/keytoolgenkeypair.go
pkg/generator/keytoolgenkeypair_test.go
pkg/generator/keytoolgenseckey.go
pkg/generator/keytoolgenseckey_test.go
pkg/generator/keytoolimportcert.go
pkg/generator/keytoolimportpassword.go
pkg/generator/keytoolimportstore.go
pkg/generator/keytoolimportstore_test.go

Change Keytool to manage all temporary paths
Closes #95

Change Keytool to manage all temporary paths

---

README.md

Add additional information regarding secret manager setup

Add additional information to the README.md

---

api/v1alpha1/secretagentconfiguration_types.go
config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
controllers/secretagentconfiguration_controller.go

1. Add state to the additionalPrinterColumns with the state of the SACs  e.a. `kubectl get sac --all`
1. Write secret to k8s after processing all its keys
Closes #130
Closes #131

Controller improvements

---

README.md
api/v1alpha1/secretagentconfiguration_types.go
config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
config/samples/secretManager/cloud-credentials.yaml
controllers/secretagentconfiguration_controller.go
pkg/secretsmanager/secretsmanager.go

Need to update the readme still.

Add Azure Keyvault support

---

controllers/secretagentconfiguration_controller.go

* Fix bug loading cloud credentials temp files
* Errors when trying to load the credentials file. File not found

Fix bug loading cloud credentials temp files

---

controllers/secretagentconfiguration_controller.go

Handle out-of-order self-references in secrets
Closes #148

Handle out-of-order self-references in secrets

---

Makefile

Fix typo in the Makefile's `release` target

Fix typo in the Makefile

---

controllers/secretagentconfiguration_controller.go

1. Remove `watchOwnedObjects` logic
1. Remove `mgr.GetFieldIndexer().IndexField()` installation
Closes #155

Remove watchOwnedObjects

---

Makefile
config/ha/kustomization.yaml
config/ha/pdb.yaml
go.mod

1. Add a PodDisruptionBudget to the deployment
Closes #160

Add a PodDisruptionBudget to the deployment

---

config/manager/manager.yaml
main.go

Add readinessProbe and livenessProbe support
Closes #164

Add readinessProbe and livenessProbe support

---

README.md
main.go

1. Add message on how to disable metrics-server
1. Add runtime args to the README.md
Closes #35

Add message on how to disable metrics-server

---

config/ha/pdb.yaml

1. Change PodDisruptionBudget for HA deployments
1. Set minAvailable to 1

Change PodDisruptionBudget for HA deployments

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.goreleaser.yml

Remove unused `VERSION` from goreleaser files

Remove unused VERSION from goreleaser files

---

.goreleaser.yml

Change name template of releases

Change name template of releases

---

Makefile
api/v1alpha1/secretagentconfiguration_types.go
config/crd/bases/secret-agent.secrets.forgerock.io_secretagentconfigurations.yaml
config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml
pkg/generator/truststore.go
pkg/generator/truststore_test.go
pkg/secretsmanager/secretsmanager_integration_test.go

feat: Add PEM format output for trust stores

---

pkg/generator/generator.go

1. Add log entry when loading from secret manager
1. Change "preparing secret" to debug only
Closes #185

Add log entry when loading from secret manager

---

.github/workflows/cluster_deploy.yaml
config/default/manager_auth_proxy_patch.yaml

Adds a Github action that creates a cluster via kind, installs the
operator then creates a CRD making sure that it reaches a status of
completed. Then makes sure all the secrets are created. It doesn't
validate content.

add new kind workflow

---

config/rbac/role.yaml
controllers/secretagentconfiguration_controller.go

https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
ref: CLOUD-3237

feat: Support clusters with OwnerReferencesPermissionEnforcement enabled

---

.github/workflows/release.yaml

Run automatic docker builds as github actions

Run automatic docker builds as GitHub actions

---

api/v1alpha1/secretagentconfiguration_types_test.go
api/v1alpha1/secretagentconfiguration_webhook.go

fix: remove uneeded validation in the webook for trusstores.

---

config/rbac/role.yaml
controllers/secretagentconfiguration_controller.go

1. Update RBAC to improve openShift support
1. Assign * permissions to the /finalizers endpoint

Fix: Update RBAC to improve openShift support

---

config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml

Duplicate comments on importing additional keys to a trustore to all truststores.
ref: CLOUD-3362

chore: Duplicate import comments to all truststore objects.

---

README.md

roadmap readme

---

charts/Makefile
charts/secret-agent/.helmignore
charts/secret-agent/Chart.yaml
charts/secret-agent/templates/NOTES.txt
charts/secret-agent/templates/_helpers.tpl
charts/secret-agent/templates/crds/secretagentconfigurations.yaml
charts/secret-agent/templates/deployment.yaml
charts/secret-agent/templates/mutating-webhook-configuration.yaml
charts/secret-agent/templates/rbac.yaml
charts/secret-agent/templates/service.yaml
charts/secret-agent/templates/serviceaccount.yaml
charts/secret-agent/templates/tests/test-connection.yaml
charts/secret-agent/templates/validating-webhook-configuration.yaml
charts/secret-agent/values.yaml

Get helm chart version from Chart.yaml.
ref: CLOUD-4105

feat: POC: Integrate ForgeOps install into terraform modules.

---

Dockerfile
charts/secret-agent/templates/deployment.yaml
config/manager/manager.yaml
config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml

Update base image.
ref: CLOUD-4161

fix: Update base openjdk image to address vulnerabilities

---

Dockerfile
charts/secret-agent/templates/deployment.yaml
config/manager/manager.yaml
config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml

Update JDK version to remove high vulnerability in openssl library
ref: FORGEOPS-4603

chore: Update the jdk version to remove high vulnerability

---

Dockerfile
charts/secret-agent/templates/deployment.yaml
config/manager/manager.yaml

Update 2nd openjdk entry.
ref: FORGEOPS-5166

fix: Update 2nd openjdk entry

---

charts/secret-agent/values.yaml
config/default/manager_auth_proxy_patch.yaml

Changing to use different kube-rbac-proxy

---

Dockerfile
charts/secret-agent/Chart.yaml
charts/secret-agent/templates/deployment.yaml
config/manager/manager.yaml

Use latest debian stable to resolve vulnerabilities.
